# Generated by Django 5.0.1 on 2024-01-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmId', models.IntegerField(max_length=64, unique=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
