# Generated by Django 5.0.1 on 2024-01-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repricer', '0002_alter_monitorids_nmid'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorids',
            name='article',
            field=models.CharField(default=1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
