# Generated by Django 5.0.1 on 2024-01-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repricer', '0004_remove_monitorids_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitorids',
            options={'verbose_name_plural': 'Мониторинг артикулов'},
        ),
    ]
