version: '3'

services:
#  rabbitmq:
#    image: rabbitmq:management
#    ports:
#      - "5672:5672"
#      - "15672:15672"

  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: marketprod
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
#    networks:
#      - marketprod-network


  web:
    build:
      context: ./
    depends_on:
      - pg
    ports:
      - "8000:8000"
#    networks:
#      - marketprod-network
  #    entrypoint:
#      DEBUG: "False"

#  networks:
#    marketprod-network:
#      driver: bridge

